version: '3.2'

networks:
  base:
    external: true

services:
  cambium-report:
    image: jbraconig/cambium-reports
    volumes:
      - /reports:/data
    environment:
      CAMBIUM_HOST: "127.0.0.1"
      CAMBIUM_CLIENT_ID: ""
      CAMBIUM_SECRET: ""
      #CAMBIUM_DATA_COLUMNS: ""
      CAMBIUM_TIME_SECONDS: "300"
    networks: 
      - base
    logging:
      driver: json-file
      options:
        max-size: 10m
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

