version: '3.8'

services:
  cambium-report:
    image: cambium-reports
    volumes:
      - /reports:/data
    environment:
      CAMBIUM_HOST: "cnmaestro"
      CAMBIUM_CLIENT_ID: ""
      CAMBIUM_SECRET: ""
      #CAMBIUM_DATA_COLUMNS: ""
      CAMBIUM_TIME_SECONDS: "300"
    extra_hosts:
      - "cnmaestro:127.0.0.1"
    logging:
      driver: json-file
      options:
        max-size: 10m
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure


