version: '3.8'

services:
  cambium-report:
    image: jbraconig/cambium-reports
    volumes:
      - /home/cambium/data:/usr/src/app/data
      - /home/cambium/logs:/usr/src/app/logs
    environment:
      CAMBIUM_HOST: "cnmaestro"
      CAMBIUM_CLIENT_ID: ""
      CAMBIUM_CLIENT_SECRET: ""
      #CAMBIUM_DATA_COLUMNS: ""
      CAMBIUM_INTERVAL: "20"
    extra_hosts:
      - "cnmaestro:127.0.0.1"
    logging:
      driver: json-file
      options:
        max-size: 10m
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure


